<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWPF>false</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Configuration>Debug</Configuration>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonLingo.Core\MonLingo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" />
  </ItemGroup>

</Project>
